// Generated by TNCF Temanggung-WebApp Builder | Created by @rochmadjeka
// Updated: PWA API Mode — semua fungsi bisa dipanggil via fetch() dari GitHub Pages

/**
 * ============================================================
 *  KONFIGURASI — WAJIB DIISI SETELAH DEPLOY
 * ============================================================
 *  1. Deploy GAS sebagai Web App:
 *     Extensions → Apps Script → Deploy → New Deployment
 *     Type: Web App | Execute as: Me | Who has access: Anyone
 *  2. Copy Deployment URL → paste ke index.html di variabel GAS_URL
 * ============================================================
 */

// ─── CORS Helper ─────────────────────────────────────────────────────────────
function setCORSHeaders() {
  return ContentService.createTextOutput()
    .setMimeType(ContentService.MimeType.JSON);
}

function jsonResponse(data) {
  return ContentService
    .createTextOutput(JSON.stringify(data))
    .setMimeType(ContentService.MimeType.JSON);
}

// ─── doGet: health check & CORS preflight ────────────────────────────────────
function doGet(e) {
  // Kalau ada parameter action, proses sebagai GET API
  if (e && e.parameter && e.parameter.action) {
    return handleGetAction(e.parameter.action, e.parameter);
  }
  // Default: kembalikan status OK untuk health check
  return jsonResponse({ status: 'ok', message: 'TNCF Rainfall Monitor API is running' });
}

function handleGetAction(action, params) {
  if (action === 'getSiteSettings') return jsonResponse(getSiteSettings());
  if (action === 'getNormalData')   return jsonResponse(getNormalData());
  if (action === 'getRainfallData') return jsonResponse(getRainfallData(params.role, params.site));
  if (action === 'getUsersList')    return jsonResponse(getUsersList());
  return jsonResponse({ success: false, message: 'Unknown GET action: ' + action });
}

// ─── doPost: router utama untuk semua operasi CRUD ───────────────────────────
function doPost(e) {
  try {
    const payload = JSON.parse(e.postData.contents);
    const action  = payload.action;

    switch (action) {
      case 'loginUser':        return jsonResponse(loginUser(payload.data));
      case 'saveRainfallData': return jsonResponse(saveRainfallData(payload.data));
      case 'deleteData':       return jsonResponse(deleteData(payload.data.id));
      case 'getUsersList':     return jsonResponse(getUsersList());
      case 'saveUser':         return jsonResponse(saveUser(payload.data));
      case 'deleteUser':       return jsonResponse(deleteUser(payload.data.username));
      case 'getSiteSettings':  return jsonResponse(getSiteSettings());
      case 'saveSiteSetting':  return jsonResponse(saveSiteSetting(payload.data));
      case 'deleteSiteSetting':return jsonResponse(deleteSiteSetting(payload.data.site));
      case 'getNormalData':    return jsonResponse(getNormalData());
      case 'saveNormalData':   return jsonResponse(saveNormalData(payload.data));
      case 'getRainfallData':  return jsonResponse(getRainfallData(payload.data.role, payload.data.site));
      default:
        return jsonResponse({ success: false, message: 'Unknown action: ' + action });
    }
  } catch(err) {
    return jsonResponse({ success: false, message: 'Server error: ' + err.toString() });
  }
}

// ─── Setup Database ───────────────────────────────────────────────────────────
function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  
  let userSheet = ss.getSheetByName('Users');
  if (userSheet) ss.deleteSheet(userSheet); 
  userSheet = ss.insertSheet('Users');
  userSheet.appendRow(['Username', 'Password', 'Nama', 'Role', 'Site']);
  
  const users = [
    ['DAWAM', 'SUPER26', 'DAWAM', 'MANAGER', 'ALL'],
    ['AGUNG S', 'SUPER26', 'AGUNG S', 'MANAGER', 'ALL'],
    ['SLAMET S', 'SUPER26', 'SLAMET S', 'MANAGER', 'ALL'],
    ['AR LATIF', 'SUPER26', 'AR LATIF', 'MANAGER', 'ALL'],
    ['ADMIN', 'ADMIN26', 'ADMIN', 'ADMIN', 'ALL'],
    ['TEMANGGUNG', 'TMG26', 'STAFF TEMANGGUNG', 'STAFF', 'TEMANGGUNG'],
    ['MRANGGEN', 'MRG26', 'STAFF MRANGGEN', 'STAFF', 'MRANGGEN'],
    ['MADURA', 'MDR26', 'STAFF MADURA', 'STAFF', 'MADURA'],
    ['LOMBOK', 'LBK26', 'STAFF LOMBOK', 'STAFF', 'LOMBOK'],
    ['BLITAR', 'BLT26', 'STAFF BLITAR', 'STAFF', 'BLITAR'],
    ['TEGAL', 'TGL26', 'STAFF TEGAL', 'STAFF', 'TEGAL'],
    ['PEMALANG', 'PMG26', 'STAFF PEMALANG', 'STAFF', 'PEMALANG']
  ];
  userSheet.getRange(2, 1, users.length, 5).setValues(users);

  let dataSheet = ss.getSheetByName('RainfallData');
  if (!dataSheet) {
    dataSheet = ss.insertSheet('RainfallData');
    dataSheet.appendRow(['ID', 'Tanggal', 'Site', 'OBS', 'Data Ombro', 'Nilai CH', 'User Input', 'Timestamp']);
  }
  
  let settingsSheet = ss.getSheetByName('Settings');
  if (settingsSheet) ss.deleteSheet(settingsSheet);
  settingsSheet = ss.insertSheet('Settings');
  settingsSheet.appendRow(['Site', 'OBS']);
  const mapping = [
    ['TEMANGGUNG', 'SIN1,SIN2,SIN3,SUM1,SUM2,SUM3,SWH1,SWH2,TLO'],
    ['MRANGGEN', 'MRG1,MRG2,MRG3'],
    ['MADURA', 'GNG1,TGL1,TGL2,TGL3,GNG2,SWH'],
    ['LOMBOK', 'LBK'],
    ['BLITAR', 'BLT'],
    ['TEGAL', 'TGL'],
    ['PEMALANG', 'PMG']
  ];
  settingsSheet.getRange(2, 1, mapping.length, 2).setValues(mapping);

  let normalSheet = ss.getSheetByName('NormalData');
  if (normalSheet) ss.deleteSheet(normalSheet);
  normalSheet = ss.insertSheet('NormalData');
  normalSheet.appendRow(['Site', 'Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des']);
  const defaultNormals = [
    ['TEMANGGUNG', 384, 336, 314, 268, 162, 92, 43, 41, 62, 165, 284, 336],
    ['MRANGGEN', 0,0,0,0,0,0,0,0,0,0,0,0],
    ['MADURA', 0,0,0,0,0,0,0,0,0,0,0,0],
    ['LOMBOK', 0,0,0,0,0,0,0,0,0,0,0,0],
    ['BLITAR', 0,0,0,0,0,0,0,0,0,0,0,0],
    ['TEGAL', 0,0,0,0,0,0,0,0,0,0,0,0],
    ['PEMALANG', 0,0,0,0,0,0,0,0,0,0,0,0]
  ];
  normalSheet.getRange(2, 1, defaultNormals.length, 13).setValues(defaultNormals);
  return "Setup Berhasil!";
}

// ─── Authentication ───────────────────────────────────────────────────────────
function loginUser(formData) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  const data  = sheet.getDataRange().getValues();
  const { username, password } = formData;
  for (let i = 1; i < data.length; i++) {
    if (data[i][0].toString().toUpperCase() === username.toUpperCase().trim() &&
        data[i][1].toString() === password) {
      return { success: true, user: { username: data[i][0], nama: data[i][2], role: data[i][3], site: data[i][4] } };
    }
  }
  return { success: false, message: 'User ID atau Password salah!' };
}

// ─── Rainfall Data CRUD ───────────────────────────────────────────────────────
function saveRainfallData(payload) {
  try {
    const sheet   = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('RainfallData');
    const nilaiCH = Math.round((parseFloat(payload.ombro) / 95) * 10);
    const id      = payload.id || "CH-" + new Date().getTime();
    const rowData = [
      id,
      Utilities.formatDate(new Date(payload.tanggal), Session.getScriptTimeZone(), "yyyy-MM-dd"),
      payload.site, payload.obs, payload.ombro, nilaiCH, payload.userInput, new Date()
    ];
    if (payload.isEdit) {
      const allData  = sheet.getDataRange().getValues();
      const rowIndex = allData.findIndex(r => r[0] == payload.id);
      if (rowIndex !== -1) sheet.getRange(rowIndex + 1, 1, 1, rowData.length).setValues([rowData]);
    } else {
      sheet.appendRow(rowData);
    }
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
}

function getRainfallData(role, userSite) {
  try {
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('RainfallData');
    if (!sheet) return { success: true, data: [] };
    const rawData = sheet.getDataRange().getValues();
    const headers = rawData.shift();
    let filtered  = rawData;
    if (role === 'STAFF') filtered = rawData.filter(row => row[2] === userSite);
    const cleanData = filtered.map(row => {
      let obj = {};
      headers.forEach((header, i) => {
        let val = row[i];
        if (val instanceof Date) val = Utilities.formatDate(val, Session.getScriptTimeZone(), "yyyy-MM-dd");
        obj[header.replace(/\s/g, '_')] = (val === null || val === undefined) ? "" : val;
      });
      return obj;
    }).reverse();
    return { success: true, data: cleanData };
  } catch(e) { return { success: false, message: e.toString() }; }
}

function deleteData(id) {
  try {
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('RainfallData');
    const data  = sheet.getDataRange().getValues();
    const idx   = data.findIndex(r => r[0] == id);
    if (idx !== -1) { sheet.deleteRow(idx + 1); return { success: true }; }
    return { success: false, message: "ID tidak ditemukan" };
  } catch(e) { return { success: false, message: e.toString() }; }
}

// ─── Users ────────────────────────────────────────────────────────────────────
function getUsersList() {
  const data = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users').getDataRange().getValues();
  data.shift();
  return { success: true, data: data.map(r => ({ username:r[0], password:r[1], nama:r[2], role:r[3], site:r[4] })) };
}
function saveUser(p) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  const data  = sheet.getDataRange().getValues();
  if (p.isEdit) {
    const idx = data.findIndex(r => r[0] == p.oldUsername);
    if (idx !== -1) sheet.getRange(idx+1,1,1,5).setValues([[p.username.toUpperCase(),p.password,p.nama,p.role,p.site]]);
  } else {
    sheet.appendRow([p.username.toUpperCase(),p.password,p.nama,p.role,p.site]);
  }
  return { success: true };
}
function deleteUser(u) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  const data  = sheet.getDataRange().getValues();
  const idx   = data.findIndex(r => r[0] == u);
  if (idx !== -1) sheet.deleteRow(idx+1);
  return { success: true };
}

// ─── Site Settings ────────────────────────────────────────────────────────────
function getSiteSettings() {
  const data = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Settings').getDataRange().getValues();
  data.shift();
  let m = {};
  data.forEach(r => { m[r[0]] = r[1].toString().split(',').map(s => s.trim()); });
  return { success: true, data: m };
}
function saveSiteSetting(p) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Settings');
  const data  = sheet.getDataRange().getValues();
  const idx   = data.findIndex(r => r[0] == p.oldSiteName);
  if (idx !== -1) sheet.getRange(idx+1,1,1,2).setValues([[p.site,p.obs]]);
  else sheet.appendRow([p.site,p.obs]);
  return { success: true };
}
function deleteSiteSetting(s) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Settings');
  const data  = sheet.getDataRange().getValues();
  const idx   = data.findIndex(r => r[0] == s);
  if (idx !== -1) sheet.deleteRow(idx+1);
  return { success: true };
}

// ─── Normal Data ──────────────────────────────────────────────────────────────
function getNormalData() {
  const data = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('NormalData').getDataRange().getValues();
  data.shift();
  let m = {};
  data.forEach(r => { m[r[0]] = r.slice(1,13); });
  return { success: true, data: m };
}
function saveNormalData(p) {
  const sheet   = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('NormalData');
  const data    = sheet.getDataRange().getValues();
  const idx     = data.findIndex(r => r[0] == p.site);
  const rowData = [p.site, ...p.values];
  if (idx !== -1) sheet.getRange(idx+1,1,1,13).setValues([rowData]);
  else sheet.appendRow(rowData);
  return { success: true, message: 'Simpan berhasil' };
}
